version: 2.1

jobs:
  build:
    macos:
      xcode: "15.2.0" # Adjust the Xcode version as needed
    environment:
      FLUTTER_ROOT: $HOME/flutter
      PATH: "$HOME/flutter/bin:$PATH"
    steps:
      - checkout
      
      # Install required dependencies
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            
      - run:
          name: Install CocoaPods
          command: |
            sudo gem install cocoapods
            
      # Restore Cocoapods dependencies
      - run:
          name: Cocoapods install
          command: |
            pod install
            
      # Build the Xcode project
      - run:
          name: Build project
          command: |
            xcodebuild -project iAppConverter.xcodeproj -scheme iAppConverter build
