name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Change Xcode Build Output Directory
        run: |
          mkdir -p $HOME/xcode_build_output
          defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks `sysctl -n hw.logicalcpu`
          defaults write com.apple.dt.Xcode BuildSystemScheduleInherentlyParallelCommandsExclusively -bool NO
          defaults write com.apple.dt.Xcode BuildSystemUseTaskSandbox YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode BuildSystemDiagnosticsYES
          defaults write com.apple.dt.Xcode BuildSystemScheduleInherentlyParallelCommandsExclusively NO
          defaults write com.apple.dt.Xcode BuildSystemUseParallelization YES
          defaults write com.apple.dt.Xcode DistributedBuildCacheEnabled YES
          defaults write com.apple.dt.Xcode DistributedBuildCacheUsingServer YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IDEIndexDisableStateScanning YES
          defaults write com.apple.dt.Xcode IndexerActivityShowItem YES
          defaults write com.apple.dt.Xcode IDEIndexerActivityShowItem YES
          echo "Xcode build output directory changed to $HOME/xcode_build_output"
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -derivedDataPath "$HOME/xcode_build_output" | xcpretty && exit ${PIPESTATUS[0]}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xcode-build-output
          path: $HOME/xcode_build_output
